const GET_ASSISTANT_RESPONSE_CHAT_URL = import.meta.env.VITE_GET_ASSISTANT_RESPONSE_CHAT
const API_ENDPOINTS = {
        GET_ASSISTANT_RESPONSE_CHAT: GET_ASSISTANT_RESPONSE_CHAT_URL
        };

export default API_ENDPOINTS;  